blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Contribution Guide
    url: https://github.com/JINSOLdev/sticker-diary-FE/blob/main/.github/CONTRIBUTING.md
    about: ë¸Œëœì¹˜ ì „ëµê³¼ ê¸°ì—¬ ê°€ì´ë“œë¥¼ ë¨¼ì € í™•ì¸í•´ì£¼ì„¸ìš”.
